/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        colors: {
                "surface-bright": "#393841",
                "tertiary": "#ffb783",
                "primary-fixed": "#e1e0ff",
                "on-primary-fixed": "#07006c",
                "surface": "#13131b",
                "inverse-primary": "#494bd6",
                "on-tertiary": "#4f2500",
                "surface-tint": "#c0c1ff",
                "secondary-container": "#00a572",
                "on-primary-container": "#0d0096",
                "on-surface": "#e4e1ed",
                "on-secondary-fixed": "#002113",
                "surface-container-low": "#1b1b23",
                "secondary-fixed-dim": "#4edea3",
                "surface-container-lowest": "#0d0d15",
                "outline": "#908fa0",
                "surface-dim": "#13131b",
                "error-container": "#93000a",
                "on-secondary-container": "#00311f",
                "primary-container": "#8083ff",
                "on-error-container": "#ffdad6",
                "primary-fixed-dim": "#c0c1ff",
                "on-error": "#690005",
                "on-background": "#e4e1ed",
                "inverse-on-surface": "#303038",
                "tertiary-fixed-dim": "#ffb783",
                "surface-variant": "#34343d",
                "secondary-fixed": "#6ffbbe",
                "tertiary-fixed": "#ffdcc5",
                "surface-container": "#1f1f27",
                "on-tertiary-fixed-variant": "#703700",
                "on-primary": "#1000a9",
                "on-surface-variant": "#c7c4d7",
                "surface-container-high": "#292932",
                "outline-variant": "#464554",
                "error": "#ffb4ab",
                "on-secondary": "#003824",
                "on-secondary-fixed-variant": "#005236",
                "secondary": "#4edea3",
                "tertiary-container": "#d97721",
                "surface-container-highest": "#34343d",
                "background": "#13131b",
                "on-tertiary-fixed": "#301400",
                "primary": "#c0c1ff",
                "on-primary-fixed-variant": "#2f2ebe",
                "inverse-surface": "#e4e1ed",
                "on-tertiary-container": "#452000"
        },
        borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
        },
        spacing: {
                "margin_md": "24px",
                "margin_sm": "16px",
                "margin_lg": "40px",
                "main_max_width": "800px",
                "header_height": "52px",
                "sidebar_width": "280px",
                "gutter": "24px"
        },
        fontFamily: {
                "headline-md": ["Inter"],
                "display-lg-mobile": ["Inter"],
                "body-base": ["Inter"],
                "label-mono": ["JetBrains Mono"],
                "display-lg": ["Inter"],
                "label-upper": ["Inter"],
                "body-sm": ["Inter"]
        },
        fontSize: {
                "headline-md": ["20px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500" }],
                "display-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "body-base": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "label-mono": ["12px", { "lineHeight": "1.5", "letterSpacing": "0.02em", "fontWeight": "500" }],
                "display-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "label-upper": ["11px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
                "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
        }
    },
  },
  plugins: [],
}
